export const IPC_CHANNELS = {
	getBootstrap: 'pumpd-desktop:get-bootstrap',
	stateChanged: 'pumpd-desktop:state-changed',
	runAction: 'pumpd-desktop:run-action',
	getSimulatorState: 'pumpd-desktop:simulator:get-state',
	simulatorStateChanged: 'pumpd-desktop:simulator:state-changed',
	refreshSimulators: 'pumpd-desktop:simulator:refresh',
	requestSimulatorConfirmation: 'pumpd-desktop:simulator:request-confirmation',
	runSimulatorAction: 'pumpd-desktop:simulator:run-action',
	cancelSimulatorJob: 'pumpd-desktop:simulator:cancel-job',
	getSimulatorCaptureAccess: 'pumpd-desktop:simulator:capture:get-access',
	getSimulatorCaptureRetention: 'pumpd-desktop:simulator:capture:get-retention',
	runSimulatorCaptureOperation: 'pumpd-desktop:simulator:capture:run-operation',
	runSimulatorOnboardingOperation:
		'pumpd-desktop:simulator:onboarding:run-operation',
	getSlimmingState: 'pumpd-desktop:slimming:get-state',
	slimmingStateChanged: 'pumpd-desktop:slimming:state-changed',
	refreshSlimming: 'pumpd-desktop:slimming:refresh',
	setSlimmingEnabled: 'pumpd-desktop:slimming:set-enabled',
	acknowledgeSlimmingCompatibility:
		'pumpd-desktop:slimming:acknowledge-compatibility',
	requestSlimmingConfirmation: 'pumpd-desktop:slimming:request-confirmation',
	runSlimmingAction: 'pumpd-desktop:slimming:run-action',
	cancelSlimmingJob: 'pumpd-desktop:slimming:cancel-job',
	getRecipeState: 'pumpd-desktop:recipe:get-state',
	recipeStateChanged: 'pumpd-desktop:recipe:state-changed',
	getRecipe: 'pumpd-desktop:recipe:get',
	getRecipeEvidence: 'pumpd-desktop:recipe:get-evidence',
	saveRecipe: 'pumpd-desktop:recipe:save',
	requestRecipeRunConfirmation: 'pumpd-desktop:recipe:request-confirmation',
	runRecipe: 'pumpd-desktop:recipe:run',
	cancelRecipeRun: 'pumpd-desktop:recipe:cancel-run',
	runRecipeFileOperation: 'pumpd-desktop:recipe:file-operation',
	getBuildInsightsState: 'pumpd-desktop:build-insights:get-state',
	buildInsightsStateChanged: 'pumpd-desktop:build-insights:state-changed',
	runBuildInsightsOperation: 'pumpd-desktop:build-insights:run-operation',
} as const;
